### ISSUE TITLE
Does "partial mutual information" here mean "conditional mutual information"?

### ISSUE THREAD

**Issue by lupupu** [paulbrodersen/entropy_estimators#13]
https://github.com/paulbrodersen/entropy_estimators/blob/11fad3c048d681b5e2117288d051734b2e886b7b/entropy_estimators/continuous.py#L336

**Comment by paulbrodersen** [comment]
The two terms are often used interchangeably. 

I give the mathematical definition two lines later in the doc-string.
I(X,Y|Z) = H(X,Z) + H(Y,Z) - H(X,Y,Z) - H(Z)

Basically, you are trying to compute the mutual information between process X and Y while ignoring the contributions of Z to both X and Y. 

Does that answer your question?

**Comment by paulbrodersen** [comment]
Closing the issue due to inactivity. Feel free to re-open, if necessary.
