### ISSUE TITLE
Error occurred with "get_imin"

### ISSUE THREAD

**Issue by wang422003** [paulbrodersen/entropy_estimators#15]
Many thanks for the fantastic software, which I have been searching for for some days.

I tried to test the PID calculation and realized that there might be a typo in line 542 of "continuous.py": "for ii in range(N):", where "N" seemed to be undefined. 

I am not sure whether this is an error resulting from my "violently" integration of the "entropy_estimators" into my script or just because of my dizzy mind after coding for days.

Many thanks in advance if you can help me to deal with this error.

**Comment by paulbrodersen** [comment]
Hi, thanks for the heads up. No idea why and how that "n" got capitalized. Should be fixed in the latest version on github. Let me know if you run into any further issues!
